Better validation error when metadata element not found
It was showing just `IndexError: list index out of range` so it's hard to know
what's wrong or where the problem is.  Now it prints out the first 800
characters of the page (or composite-chapter in this case) so we have an idea
of where this problem is.  For example:

```
cnxepub ERROR Metadata (data-type="metadata") not found:
<div xmlns="http://www.w3.org/1999/xhtml" xmlns:m="http://www.w3.org/1998/Math/MathML" class="os-eoc os-chapter-review-container" data-type="composite-chapter" data-uuid-key=".chapter-review"><h2 data-type="document-title"><span class="os-text">Chapter Review</span></h2><div class="os-eoc os-concept-container" data-type="composite-page"><h3 data-type="title"><span class="os-text">Concept Items</span></h3><div data-type="metadata" style="display: none;">
      <h1 data-type="document-title" itemprop="name">Key Equations</h1>

      <div class="authors">
        By:
<span id="author-1_copy_5" itemscope="itemscope" itemtype="http://schema.org/Person" itemprop="author" data-type="author">
            <a href="os_hsphysics" itemprop="url" data-type="cnx-id">os_hsphysics</a>
          </s...
Traceback (most recent call last):
  File "/code/venv/lib/python3.6/site-packages/cnxepub/adapters.py", line 473, in _adapt_single_html_tree
    child.xpath('./*[@data-type="metadata"]')[0])
IndexError: list index out of range
```